### ISSUE TITLE
Display list of updates and comments on the front page

### ISSUE THREAD

**Issue by friedger** [openintents/app-center#3]
There should be 
* one section on the front page that shows a list of the 10 last updates (`OwnerComment`)
* one section on the front page that shows a list of the 10 last comments (`UserComment`)

This issue involves:
* add api to fetch the updates/comments on radiks (similar to banter)
* add the the UI to display the lists (reusing existing components) fetch from the new api on the index page.

**Comment by x5engine** [comment]
clear issue, I will other questions here too

**Comment by friedger** [comment]
First part done by #8

**Comment by friedger** [comment]
Fixed in 1.5
