### ISSUE TITLE
Style footer to be clearly distinct from app descriptions

### ISSUE THREAD

**Issue by njordhov** [openintents/app-center#37]
The footer could benefit from styling that clearly separates it from the rest of the page, like a darker color and/or border on top. Currently, the openintents info in the footer appears confusingly as if it is a continuation of the app info on the page (see below).

![image](https://user-images.githubusercontent.com/219448/67329661-0376c100-f4d0-11e9-8e58-2c50e3254d2e.png)

**Comment by friedger** [comment]
horizontal line has been added
